### ISSUE TITLE
Source code does not follow the lectures from the course

### ISSUE THREAD

**Issue by tikomir** [maryellenteaches/SpringData2#1]
Source code does not follow the lectures from the course. E.g. source code in the branches 3-3 and 3-4 are identical. Also, source code doesn't contain complete annotations. Take for example annotations for the attribute _courses_ of the _Student_ entity etc. This repo needs update.

**Comment by MiellyEllen** [comment]
Hi tikomir. 

1. Yes 3-3 and 3-4 are identical. That's a choice i made and don't see a problem with it as the video guides the learner to refer to the appropriate files.
2. I don't follow your comment about an annotation not being "complete". Do you mean the @OneToMany annotation on courses? it works fine.

**Comment by tikomir** [comment]
Hi Mary.

Some of annotations and their attributes given in the lecture 2.4 "Map multiple tables to Java classes" cannot be seen anywhere in the code e.g. annotation _@JoinTable_ and atributes _nullable_, _joinColumns_, _inverseJoinColumns_ that belong to the _Student_ entity.
